
window.mallaData = [
  { id: "matematicas_basicas", nombre: "Matemáticas Básicas", semestre: 1, prerrequisitos: [] },
  { id: "dibujo_basico", nombre: "Dibujo Básico", semestre: 1, prerrequisitos: [] },
  { id: "taller_ingenieria", nombre: "Taller de Ingeniería Electrónica", semestre: 1, prerrequisitos: [] },
  { id: "programacion", nombre: "Programación de Computadores", semestre: 1, prerrequisitos: [] },
  { id: "desarrollo_sostenible", nombre: "Ingeniería y Desarrollo Sostenible", semestre: 1, prerrequisitos: [] },
  { id: "calculo_diferencial", nombre: "Cálculo Diferencial", semestre: 1, prerrequisitos: ["matematicas_basicas"] },
  { id: "calculo_integral", nombre: "Cálculo Integral", semestre: 2, prerrequisitos: ["calculo_diferencial"] },
  { id: "fund_mecanica", nombre: "Fundamentos de Mecánica", semestre: 2, prerrequisitos: ["calculo_diferencial"] },
  { id: "algebra_lineal", nombre: "Álgebra Lineal", semestre: 2, prerrequisitos: ["matematicas_basicas"] },
  { id: "tecnologia_mecanica", nombre: "Tecnología Mecánica Básica", semestre: 2, prerrequisitos: ["dibujo_basico", "desarrollo_sostenible"] },
  { id: "electricidad_magnetismo", nombre: "Fund. Electricidad y Magnetismo", semestre: 3, prerrequisitos: ["fund_mecanica", "calculo_integral"] },
  { id: "circuitos", nombre: "Circuitos Eléctricos I", semestre: 3, prerrequisitos: ["taller_ingenieria", "algebra_lineal"] },
  { id: "electronica_analoga", nombre: "Electrónica Análoga I", semestre: 3, prerrequisitos: ["circuitos"] },
  { id: "electronica_digital", nombre: "Electrónica Digital I", semestre: 3, prerrequisitos: ["programacion"] },
  { id: "estatica", nombre: "Principios de Estática", semestre: 3, prerrequisitos: ["algebra_lineal"] },
  { id: "calculo_varias", nombre: "Cálculo Varias Variables", semestre: 3, prerrequisitos: ["calculo_integral", "algebra_lineal"] },
  { id: "probabilidad", nombre: "Probabilidad y Estadística Fundamental", semestre: 3, prerrequisitos: ["calculo_diferencial"] },
  { id: "quimica", nombre: "Principios de Química", semestre: 3, prerrequisitos: [] },
  { id: "ecuaciones", nombre: "Ecuaciones Diferenciales", semestre: 4, prerrequisitos: ["calculo_integral", "algebra_lineal"] },
  { id: "poo", nombre: "Programación Orientada a Objetos", semestre: 4, prerrequisitos: ["programacion"] },
  { id: "dinamica", nombre: "Principios de Dinámica", semestre: 4, prerrequisitos: ["algebra_lineal"] },
  { id: "libre_1", nombre: "Libre Elección", semestre: 4, prerrequisitos: [] },
  { id: "libre_2", nombre: "Libre Elección", semestre: 4, prerrequisitos: [] },
  { id: "variable_compleja", nombre: "Variable Compleja", semestre: 5, prerrequisitos: ["ecuaciones"] },
  { id: "optativa_fisica", nombre: "Optativa Física", semestre: 5, prerrequisitos: ["ecuaciones", "fund_mecanica"] },
  { id: "senales_1", nombre: "Señales y Sistemas I", semestre: 5, prerrequisitos: ["ecuaciones", "circuitos"] },
  { id: "estructura_datos", nombre: "Estructura de Datos", semestre: 5, prerrequisitos: ["poo"] },
  { id: "resistencia_materiales", nombre: "Resistencia de Materiales", semestre: 5, prerrequisitos: ["estatica"] },
  { id: "ciencia_materiales", nombre: "Ciencia e Ingeniería de Materiales", semestre: 5, prerrequisitos: ["tecnologia_mecanica", "quimica"] },
  { id: "eco", nombre: "Ingeniería Económica", semestre: 6, prerrequisitos: ["calculo_integral"] },
  { id: "senales_2", nombre: "Señales y Sistemas II", semestre: 6, prerrequisitos: ["variable_compleja", "senales_1"] },
  { id: "digital_i", nombre: "Electrónica Digital I", semestre: 6, prerrequisitos: ["electronica_analoga"] },
  { id: "taller_proyectos", nombre: "Taller de Proyectos Interdisciplinarios", semestre: 6, prerrequisitos: ["desarrollo_sostenible"] },
  { id: "diseno_mecatronico", nombre: "Diseño Mecatrónico", semestre: 6, prerrequisitos: ["dinamica", "resistencia_materiales"] },
  { id: "optativa_6", nombre: "Optativa", semestre: 6, prerrequisitos: ["ciencia_materiales", "resistencia_materiales"] },
  { id: "optativa_7a", nombre: "Optativa", semestre: 7, prerrequisitos: ["eco", "electricidad_magnetismo"] },
  { id: "control", nombre: "Control", semestre: 7, prerrequisitos: ["senales_2"] },
  { id: "sensores", nombre: "Sensores y Actuadores", semestre: 7, prerrequisitos: ["senales_2"] },
  { id: "redes", nombre: "Redes de Computadores", semestre: 7, prerrequisitos: ["estructura_datos"] },
  { id: "micro", nombre: "Microcontroladores I", semestre: 7, prerrequisitos: ["digital_i"] },
  { id: "optativa_7b", nombre: "Optativa", semestre: 7, prerrequisitos: ["ecuaciones"] },
  { id: "robotica", nombre: "Robótica", semestre: 8, prerrequisitos: ["control"] },
  { id: "optativa_8", nombre: "Optativa", semestre: 8, prerrequisitos: ["control"] },
  { id: "libre_3", nombre: "Libre Elección", semestre: 8, prerrequisitos: [] },
  { id: "libre_4", nombre: "Libre Elección", semestre: 8, prerrequisitos: [] },
  { id: "servomecanismos", nombre: "Servomecanismos", semestre: 8, prerrequisitos: ["diseno_mecatronico"] },
  { id: "libre_5", nombre: "Libre Elección", semestre: 8, prerrequisitos: [] },
  { id: "libre_6", nombre: "Libre Elección", semestre: 9, prerrequisitos: [] },
  { id: "libre_7", nombre: "Libre Elección", semestre: 9, prerrequisitos: [] },
  { id: "libre_8", nombre: "Libre Elección", semestre: 9, prerrequisitos: [] },
  { id: "proyecto_aplicado", nombre: "Proyecto Aplicado de Ingeniería", semestre: 9, prerrequisitos: ["robotica", "optativa_6", "servomecanismos", "sensores"] },
  { id: "taller_proyectos_2", nombre: "Taller de Proyectos Interdisciplinarios", semestre: 9, prerrequisitos: [] },
  { id: "libre_9", nombre: "Libre Elección", semestre: 10, prerrequisitos: [] },
  { id: "libre_10", nombre: "Libre Elección", semestre: 10, prerrequisitos: [] },
  { id: "trabajo_grado", nombre: "Trabajo de Grado", semestre: 10, prerrequisitos: ["proyecto_aplicado"] },
  { id: "ingles1", nombre: "Inglés I", semestre: 1, prerrequisitos: [] },
  { id: "ingles2", nombre: "Inglés II", semestre: 2, prerrequisitos: ["ingles1"] },
  { id: "ingles3", nombre: "Inglés III", semestre: 3, prerrequisitos: ["ingles2"] },
  { id: "ingles4", nombre: "Inglés IV", semestre: 4, prerrequisitos: ["ingles3"] }
];
